config/routes.rb
ForumDemo::Application.routes.draw do
  devise_for :users

  resources :boards do
    resources :posts
  end

  namespace :admin do
    resources :boards do
      resources :posts
    end
  end

  root :to => "boards#index"

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :board, :counter_cache => true
  belongs_to :user
  #default_scope :order => 'created_at DESC'
  scope :recent, :order => 'updated_at DESC'
  has_attached_file :excerpt_image, :styles => {:media => '300x300>', :thumb => '100x100>'}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_protected :is_admin

  def is_admin?
    is_admin
  end
end

app/controllers/admin/boards_controller.rb
class Admin::BoardsController < ApplicationController
  layout 'admin'
  before_filter :require_is_admin
  # GET /boards
  # GET /boards.xml
  def index
    @boards = Board.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @boards }
    end
  end

  # GET /boards/1
  # GET /boards/1.xml
#  def show
#    @board = Board.find(params[:id])
#    @posts = @board.posts
#
#    respond_to do |format|
#      format.html # show.html.erb
#      format.xml  { render :xml => @board }
#    end
#  end

  # GET /boards/new
  # GET /boards/new.xml
  def new
    @board = Board.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @board }
    end
  end

  # GET /boards/1/edit
  def edit
    @board = Board.find(params[:id])
  end

  # POST /boards
  # POST /boards.xml
  def create
    @board = Board.new(params[:board])

    respond_to do |format|
      if @board.save
        format.html { redirect_to(board_path(@board), :notice => 'Board was successfully created.') }
        format.xml  { render :xml => @board, :status => :created, :location => @board }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @board.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /boards/1
  # PUT /boards/1.xml
  def update
    @board = Board.find(params[:id])

    respond_to do |format|
      if @board.update_attributes(params[:board])
        format.html { redirect_to(board_path(@board), :notice => 'Board was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @board.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.xml
  def destroy
    @board = Board.find(params[:id])
    @board.destroy

    respond_to do |format|
      format.html { redirect_to(admin_boards_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout 'admin'
  #before_filter :require_is_admin
  before_filter :find_board
  before_filter :authenticate_user!, :except => [:index]
  # GET /posts
  # GET /posts.xml

  # GET /posts/1
  # GET /posts/1.xml

  # GET /posts/new
  # GET /posts/new.xml

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
#    @board = Board.find(params[:board_id])
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(board_post_path(@board,@post), :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
#    @board = Board.find(params[:board_id])
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(board_posts_path(@board)) }
      format.xml  { head :ok }
    end
  end
protected
  def find_board
    @board = Board.find(params[:board_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def require_is_admin
    unless (current_user && current_user.is_admin?)
      flash[:alert] = "You must be admin!"
      redirect_to root_path
    end
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  # GET /boards
  # GET /boards.xml
  def index
    @boards = Board.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @boards }
    end
  end

  # GET /boards/1
  # GET /boards/1.xml
  def show
    @board = Board.find(params[:id])
    @posts = @board.posts.recent.paginate(:page => params[:page], :per_page => 5)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @board }
    end
  end

  # GET /boards/new
  # GET /boards/new.xml

  # GET /boards/1/edit

  # POST /boards
  # POST /boards.xml

  # PUT /boards/1
  # PUT /boards/1.xml
  # DELETE /boards/1.xml
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :find_board
  # GET /posts
  # GET /posts.xml
  def index
#    @board = Board.find(params[:board_id])
    redirect_to board_path(@board)
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
#    @board = Board.find(params[:board_id])
    @post = @board.posts.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
#    @board = Board.find(params[:board_id])
    @post = @board.posts.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
#    @board = Board.find(params[:board_id])
    @post = current_user.posts.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
#    @board = Board.find(params[:board_id])
    @post = @board.posts.build(params[:post])
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to(board_posts_path(@board), :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
#    @board = Board.find(params[:board_id])
    @post = current_user.posts.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(board_post_path(@board,@post), :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
#    @board = Board.find(params[:board_id])
    @post = current_user.posts.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(board_posts_path(@board)) }
      format.xml  { head :ok }
    end
  end
protected
  def find_board
    @board = Board.find(params[:board_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/boards/_form.html.erb
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

app/views/admin/boards/edit.html.erb
<h1>Editing board</h1>

<%= form_for @board, :url => admin_board_path(@board) do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>
<%= link_to 'Show', @board %> |
<%= link_to 'Back', admin_boards_path %>

app/views/admin/boards/index.html.erb
<h1>Listing boards</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @boards.each do |board| %>
  <tr>
    <td><%= board.name %></td>
    <td><%= link_to 'Show', board %></td>
    <td><%= link_to 'Edit', edit_board_path(board) %></td>
    <td><%= link_to 'Destroy', board, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Board', new_board_path %>

app/views/admin/boards/new.html.erb
<h1>New board</h1>

<%= form_for @board, :url => admin_boards_path do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>
<%= link_to 'Back', admin_boards_path %>

app/views/admin/posts/_form.html.erb
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

app/views/admin/posts/edit.html.erb
<h1>Editing post</h1>

<%= form_for @post, :url => admin_board_post_path(@board,@post) do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>
<%= link_to 'Show', board_post_path(@board,@post) %> |
<%= link_to 'Back', board_posts_path(@board) %>

app/views/admin/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/admin/show_deleted_.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @board.name %>
</p>

<h1>Listing posts</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', board_post_path(@board,post) %></td>
    <td><%= link_to 'Edit', edit_admin_board_post_path(@board,post) %></td>
    <td><%= link_to 'Destroy', admin_board_post_path(@board,post), :confirm => 'Are you shre?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<br/>

<%= link_to 'New Post', new_admin_board_post_path(@board) %> |
<%= link_to 'Edit', edit_admin_board_path(@board) %> |
<%= link_to 'Back', admin_boards_path %>

app/views/boards/index.html.erb
<h1>Listing boards</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @boards.each do |board| %>
  <tr>
    <td><%= board.name %></td>
    <td><%= link_to 'Show', board %></td>
    <% if current_user && current_user.is_admin? %>
      <td><%= link_to 'A-Edit', edit_admin_board_path(board) %></td>
      <td><%= link_to 'A-Destroy', admin_boards_path, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<% if current_user && current_user.is_admin? %>
  <%= link_to 'A-New Board', new_admin_board_path %>
<% end %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @board.name %>
</p>

<h1>Listing posts</h1>
<table>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Content</th>
    <th>Created At</th>
    <th>Uploaded At</th>
    <th></th>
  </tr>
<% @posts.each do |post| %>
  <tr>
    <td><%= post.id %></td>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= l(post.created_at, :format => :short) %></td>
    <td><%= l(post.updated_at, :format => :short) %></td>
    <td><%= link_to 'Show', board_post_path(@board,post) %></td>
    <% if current_user && post.user == current_user %>
      <td><%= link_to 'Edit', edit_board_post_path(@board,post) %></td>
      <td><%= link_to 'Destroy', board_post_path(@board,post), :confirm => 'Are you shre?', :method => :delete %></td>
    <% end %>
    <% if current_user && current_user.is_admin? %>
      <td><%= link_to 'A-Edit', edit_admin_board_post_path(@board,post) %></td>
      <td><%= link_to 'A-Destroy', admin_board_post_path(@board,post), :confirm => 'Are you sure?', :method => :delete %> </td>
    <% end %>
  </tr>
<% end %>
</table>
<h3>Total <%= @board.posts.size %> posts</h3>
<%= will_paginate(@posts) %>
<br/>

<%= link_to 'New Post', new_board_post_path(@board) %> |
<% if current_user && current_user.is_admin? %>
  <%= link_to 'A-Edit', edit_admin_board_path(@board) %> |
<% end %>
<%= link_to 'Back', boards_path %>

app/views/common/_user_nav.erb
<div class='user_navigation'>
  <% if user_signed_in? %>
    Hi <%= current_user.email %>
    <%= link_to("Sign out", destroy_user_session_path) %>
    <% if current_user.is_admin? %>
      <%= link_to("Admin Panel", admin_boards_path) %>
    <% end %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path %>
    <%= link_to "Sign up", new_user_registration_path %>
  <% end %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ForumDemo</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <h1>Admin Panel</h1>
  <%= render :partial => "common/user_nav" %>
  <%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ForumDemo</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

  <%= render :partial => "common/user_nav" %>
  <%= yield %>

</body>
</html>

app/views/pages/welcome.html.erb
<h1>Welcome World!</h1>

app/views/posts/_form.html.erb
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class='field'>
    <%= f.label :upload_image %><br/>
    <%= f.file_field :excerpt_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= form_for @post, :url => board_post_path(@board,@post), :html => { :multipart => true } do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>
<%= link_to 'Show', board_post_path(@board,@post) %> |
<%= link_to 'Back', board_posts_path(@board) %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= form_for @post, :url => board_posts_path(@board), :html => { :multipart => true }  do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>
<%= link_to 'Back', board_posts_path(@board) %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>

<% if @post.excerpt_image %>
  <p>
  <%= image_tag(@post.excerpt_image.url) %>
  </p>
<% end %>

<% if current_user && @post.user == current_user %>
  <%= link_to 'Edit', edit_board_post_path(@board,@post) %> |
<% end %>
<% if current_user && current_user.is_admin? %>
  <%= link_to 'A-Edit', edit_admin_board_post_path(@board,@post) %> |
<% end %>
<%= link_to 'Back', board_posts_path(@board) %>